Algoritmo "Par ou Impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/06/2022
Var
   n:inteiro

Inicio

   escreva (" digite um numero: ")
   leia (n)
   se (n % 2 = 0) entao
      escreval ( n, " É um número par")
   senao
      escreval ( n, " É um numero ímpar")
   fimse


Fimalgoritmo